version: '3.8'

services:
  taskapp:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "5005:5005"
    # Overriding restart policy for faster feedback loops in dev
    restart: "no"
